import {StyleSheet} from 'react-native';
import {Colors, Fonts, Icons} from '../../Theme';
const styles = StyleSheet.create({
  MainContainer: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  bg_Image_VIew: {
    width: '45%',
    height: 140,
    // alignSelf: 'center',
    borderRadius: 20,
    elevation: 5,
    marginTop: '4%',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.grey,
    backgroundColor: Colors.white,
    justifyContent: 'space-between',
    paddingBottom: 40,
    marginHorizontal: '0.5%',
    marginHorizontal: '2%',
  },
  bg_Image: {
    width: '100%',
    height: 100,
    alignSelf: 'center',
    borderRadius: 20,
    // elevation: 5,
    borderRadius: 10,
    overflow: 'hidden',
    resizeMode: 'cover',
    // opacity: 0.8,
  },
  titleContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // Adjust the opacity value as needed
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
  },
  title: {
    color: Colors.black,
    fontSize: 14,
    fontWeight: '400',
    // marginTop: '4%',
    alignSelf: 'center',
    marginTop: '5%',
    fontFamily: Fonts.inter,
    opacity: 200,
  },
  Venue: {
    color: Colors.black,
    fontSize: 16,
    fontWeight: '6s00',
    marginTop: '4%',
    alignSelf: 'center',
    zIndex: 1,
    fontFamily: Fonts.inter,
  },
  time: {
    color: 'red',
    fontSize: 16,
    fontWeight: '600',
    // position: 'absolute',
    // bottom: '4%',
    alignSelf: 'center',
    zIndex: 1,
    fontFamily: Fonts.inter,
  },
  logo_Inside: {
    height: 20,
    width: 20,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginTop: '1%',
    borderRadius: 100,
  },
  logo_Inside_title: {
    height: 30,
    width: 30,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginTop: '1%',
    borderRadius: 100,
  },
  header_View: {
    flexDirection: 'row',
    paddingHorizontal: '2%',
    marginTop: '3%',
    marginBottom: '3%',
  },
  Sms_Text: {
    marginLeft: '25%',
    color: Colors.green,
    fontSize: 20,
    fontWeight: '7s00',
    // position: 'absolute',
    // bottom: '4%',
    alignSelf: 'center',
    zIndex: 1,
    fontFamily: Fonts.inter,
  },
});

export default styles;
