export const Colors = {
  mainBgColor: '#D8A3C9',
  secondarycolor: '#FAE1E8',
  peach: '#FABFCC',
  lightGray: '#a6a8b0',
  white: '#FFFFFF',
  placeholderColor: '#848484',
  inputBgColor: '#E7E7E7',
  inputBorderColor: '#4c505f',
  drawerBgColor: '#4b4b4b',
  white: 'white',
  ticolor: 'white',
  primary: '#CA2657',
  black: 'black',
  blockprimary: '#F486B7',
  blocksecondary: '#FEAFC5',
  playerbaground: '#A4B4CE',
  seobg: '#C5C4C4',
  green: '#439F57',
  grey: 'grey',
  mahroon: '#BA4F4F',
  buttonmain: '#EC2277',
  purple: '#AD2C88',
};
