import {StyleSheet} from 'react-native';
import {Colors, Fonts, Icons} from '../../Theme';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  bg_Image_VIew: {
    width: '95%',
    height: 250,
    alignSelf: 'center',
    borderRadius: 20,
    elevation: 5,
    marginTop: '4%',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Colors.grey,
    backgroundColor: Colors.white,

    paddingBottom: 40,
  },
  bg_Image: {
    width: '100%',
    height: 180,
    alignSelf: 'center',
    borderRadius: 20,
    // elevation: 5,
    borderRadius: 10,
    overflow: 'hidden',
    resizeMode: 'cover',
    // opacity: 0.8,
  },
  titleContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // Adjust the opacity value as needed
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
  },
  title: {
    color: Colors.green,
    fontSize: 25,
    fontWeight: '900',

    alignSelf: 'center',
    zIndex: 1,
    fontFamily: Fonts.PopinsBold,
    opacity: 200,
    zIndex: 100,
  },
  Venue: {
    color: Colors.black,
    fontSize: 17,
    fontWeight: '700',

    alignSelf: 'center',
    zIndex: 1,
    fontFamily: Fonts.inter,
  },
  time: {
    color: 'red',
    fontSize: 17,
    fontWeight: '700',
    // position: 'absolute',
    // bottom: '4%',
    alignSelf: 'center',
    zIndex: 1,
    fontFamily: Fonts.inter,
  },
  mediaPlayer: {
    flex: 1,
  },
  share_Button: {
    borderWidth: 1,
    width: '45%',
    alignItems: 'center',
    flexDirection: 'row',
    paddingVertical: '4%',
    borderRadius: 10,
    backgroundColor: Colors.green,
    // alignSelf: 'center',
    justifyContent: 'center',
    marginLeft: '3%',
    borderColor: Colors.green,
    borderWidth: 1,
    elevation: 5,
    // position: 'absolute',
    // bottom: 4,
  },
  Text_Btn: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: '600',
    // position: 'absolute',
    // bottom: '4%',
    alignSelf: 'center',
    marginLeft: '2%',
    // zIndex: 1,
    fontFamily: Fonts.inter,
  },
  header_View: {
    flexDirection: 'row',
    paddingHorizontal: '2%',
    marginTop: '3%',
    marginBottom: '3%',
  },
  Sms_Text: {
    marginLeft: '25%',
    color: Colors.green,
    fontSize: 20,
    fontWeight: '600',
    // position: 'absolute',
    // bottom: '4%',
    alignSelf: 'center',
    zIndex: 1,
    fontFamily: Fonts.inter,
  },
  description_Header: {
    color: Colors.black,
    fontSize: 20,
    fontWeight: '600',

    zIndex: 1,
    fontFamily: Fonts.inter,
  },
  description: {
    color: Colors.black,
    fontSize: 12,
    fontWeight: '400',
    width: '98%',
    alignSelf: 'center',

    zIndex: 1,
    fontFamily: Fonts.inter,
  },
  modalContainer: {
    // flex: 1,
    position: 'absolute',
    top: 0,
    height: '46%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: 'blue',
    backgroundColor: 'rgba(0, 0, 0, 0)', // Semi-transparent black background
  },
  modalContainer_Inside: {
    backgroundColor: 'red',
    height: '7%',
  },
  modalContainer_Inside2: {
    backgroundColor: 'red',
    height: '10%',
    marginTop: '68%',
  },
  top_View: {
    position: 'absolute',
    top: '0%',
    width: '100%',
    height: '7%',
    backgroundColor: Colors.green,
    flex: 1,
    zIndex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: '4%',
  },
  bottom_View: {
    position: 'absolute',
    top: '36%',
    width: '100%',
    height: '10%',
    backgroundColor: Colors.green,
    flex: 1,
    zIndex: 1,
  },
  Setting_View: {
    position: 'absolute',
    top: '9%',
    right: '14%',
    width: '13%',
    height: '5%',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    flex: 1,
    zIndex: 1,
  },
  Sms_Text: {
    color: Colors.white,
    fontSize: 22,
    fontWeight: '600',
    marginLeft: '24%',
  },
  bottom_TExt_Inside: {
    alignSelf: 'center',
    fontSize: 18,
    color: Colors.white,
    fontWeight: '600',
  },
});
export default styles;
